### ISSUE TITLE
 class SSDEntropyCalibrator(trt.IInt8EntropyCalibrator2): AttributeError: module 'tensorrt' has no attribute 'IInt8EntropyCalibrator2'

### ISSUE THREAD

**Issue by Nukul13** [NVIDIA/object-detection-tensorrt-example#1]
Hello

I am trying to run the provided script and getting the above error. 

I have Ubuntu 16.04 with CUDA-10.0, Pycuda and Tensorrt-5.0.26 installed. I am running on my system and not using docker for this. Please try to help

**Comment by GLBurnett** [comment]
Hey @Nukul13, 

It's probably because we are using different versions of TensorRT and this class was most likely renamed. The version this was tested with was TensorRT 5.1 so using 5.0 might cause some issues. 

To avoid further conflicts, I recommend using the [dockerfile](https://github.com/NVIDIA/object-detection-tensorrt-example/tree/master/dockerfiles) that comes with this repo. Otherwise you could try to install TensorRT 5.1, but I can't guarantee you won't run into other dependency mismatches in other packages. 

Cheers
